remote_theme: pages-themes/hacker@v0.2.0
title: Elvis Brevi's Blog
description: Personal blog and portfolio
show_downloads: false

# Build settings
markdown: kramdown
permalink: /posts/:title/

# Post settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag